export enum CellsActionTypes {
    MOVE_CELL = "MOVE_CELL",
    DELETE_CELL = "DELETE_CELL",
    INSERT_CELL_AFTER = "INSERT_CELL_AFTER",
    UPDATE_CELL = "UPDATE_CELL",
    FETCH_CELLS = "FETCH_CELLS",
    FETCH_CELLS_COMPLETE = "FETCH_CELLS_COMPLETE",
    FETCH_CELLS_ERROR = "FETCH_CELLS_ERROR"
}